### ISSUE TITLE
[建议]考虑加个拖放模式来选择代签名apk么？

### ISSUE THREAD

**Issue by 1nC0deWeTrust** [DeMonJavaSpace/SignatureTools#7]
文件拖放到输入框中完成代签名apk的选择。

![image](https://user-images.githubusercontent.com/25895481/224596445-de4ac19f-6e87-4aaf-b229-0bd968ca2122.png)

**Comment by iDeMonnnnnn** [comment]
JavaFx只会用一些基础的控件，代码开源，可以自己实现
